### ISSUE TITLE
Multiplex datasets

### ISSUE THREAD

**Issue by siri-ius** [benedekrozemberczki/PDN#2]
Hi,

I really like your paper and was more interested in it, so I took into multiplex datasets, and for these two datasets in table 4, it is written that both of them have 2 classes. On the other hand, you have cited DMGI paper as a source of your datasets, but DMGI paper has 3 classes for each of them. Maybe I got something wrong and clarification would help. So, could you please help me with this? Why do you have two classes instead of three and how did you implement this?

Thank you! :)

**Comment by benedekrozemberczki** [comment]
Hi there,

Yes, that dataset has a third layer which is a complete graph.

Bests,

Benedek

**Comment by siri-ius** [comment]
Hi,

for which dataset are you talking about? There are two datasets (multiplex datasets). 
Also, my question was more directed to the classes, ground truth data, and I do not see the relation to that third layer that you mentioned here.

Thanks!
